### ISSUE TITLE
[REQ] \e\ build for Nova

### ISSUE THREAD

**Issue by MarcoRavich** [skinzor/android_device_huawei_hwcan#2]
Hi there, we know that is probably abandoned, but can you consider to build \e\ (aka deGoogled LineageOS) for it ?

https://doc.e.foundation/support-topics/build-e

Last but not least, here's our post for the device in \e\ community:

https://community.e.foundation/t/device-huawei-nova/34259

Thanks in advance.

**Comment by skinzor** [comment]
@forart Hi there,

Unfortunately, I don't have free time for this nor a working Huawei Nova. It could work if there's testers and I don't think it'd be so complicated since \e\ is based on LineageOS, but my main problem is the free time.

**Comment by MarcoRavich** [comment]
Hi @skinzor, thanks for your reply.

Don't worry, we'll try to stimulate some other user/builder to do it for Nova.

Anyway we wanna share with you a couple of interesting guides that may help to build \e\ (for any other device you're actually maintaining):
https://doc.e.foundation/support-topics/build-e
https://community.e.foundation/t/howto-building-e-roms-a-beginners-guide/26371

Last but not least, we've also suggested (check [here](https://community.e.foundation/t/automated-builds-v-machine/43336)) to setup a "build (V)Machine" by modding this colab notebook to made it device agnostic:
https://github.com/viam1-dev/colab_lineage_build

Hope can "inspire" you.

Thanks in advance.
